app = "crumbs"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  
[vm]
  memory = 2048 # or 1024 (MB)
  
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Optional persistent volume for H2 file DB
[[mounts]]
  source = "crumbs_data"
  destination = "/app/data"

[checks]
  [checks.status]
    type = "http"
    port = 8080 # or your app port
    path = "/" # or "/" if no actuator
    interval = "15s"
    timeout = "5s"
