app = "crumbs"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[vm]
  memory = 512 # or 1024 (MB)
  
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Optional persistent volume for H2 file DB
[[mounts]]
  source = "crumbs_data"
  destination = "/app/data"
