spring.application.name=crumbs_new
server.port=${PORT:8080}
server.address=0.0.0.0
app.max-threads=5
spring.main.allow-circular-references=true
logging.config=classpath:logback-spring.xml
logging.file=/app/data/server.log
# Completely disable all other logs
logging.level.root=OFF
# Enable logging only for your package
logging.level.com.crumbs.trade=DEBUG
spring.web.resources.add-mappings=true
spring.main.banner-mode=off
#Database
#spring.datasource.url=jdbc:h2:file:~/trade;CACHE_SIZE=65536;CACHE_TYPE=SOFT;AUTO_RECONNECT=TRUE
#jdbc:h2:file:/app/data/trade - for fly cloud
# Database — Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres
spring.datasource.password=Athiran@2020
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true


spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anbalagan.aravind@gmail.com
spring.mail.password=fqrd jvpn wzks qlii
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000



spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.model=moonshotai/kimi-k2-instruct
spring.ai.retry.max-attempts=3
spring.ai.retry.initial-interval=1000
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
server.forward-headers-strategy=framework

spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java,src/main/resources


telegram.bot-token=${TELEGRAM_API_KEY}
telegram.chat-id=1685538818
telegram.base-url=https://api.telegram.org

# AngelOne API
angelone.api.url=https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json

# File paths
app.data.path=/app/data
app.local.resources.path=src/main/resources

scheduler.enabled=true   # ON
#scheduler.enabled=false  # OFF



