-- =====================================================
-- DATA INSERTION - All 501 NIFTY 500 Stocks
-- =====================================================

INSERT INTO FUTURES (name, sector, industry, is_nifty_50, is_nifty_next_50, is_nifty_100, is_nifty_200, is_nifty_500) VALUES
('360ONE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('3MINDIA', 'Diversified', 'Diversified', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABB', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, TRUE),
('ACC', 'Construction Materials', 'Construction Materials', FALSE, TRUE, TRUE, TRUE, TRUE),
('ACMESOLAR', 'Power', 'Power', FALSE, FALSE, FALSE, TRUE, TRUE),
('AIAENG', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('APLAPOLLO', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('AUBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('AWL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('AADHARHFC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('AARTIIND', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('AAVAS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABBOTINDIA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ACE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('ADANIENSOL', 'Power', 'Power', FALSE, FALSE, FALSE, TRUE, TRUE),
('ADANIENT', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, TRUE, TRUE),
('ADANIGREEN', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, TRUE),
('ADANIPORTS', 'Services', 'Services', TRUE, FALSE, TRUE, TRUE, TRUE),
('ADANIPOWER', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, TRUE),
('ATGL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABCAPITAL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABFRL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABLBL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABREL', 'Forest Materials', 'Forest Materials', FALSE, FALSE, FALSE, TRUE, TRUE),
('ABSLAMC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('AEGISLOG', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('AEGISVOPAK', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('AFCONS', 'Construction', 'Construction', FALSE, FALSE, FALSE, TRUE, TRUE),
('AFFLE', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, TRUE, TRUE),
('AJANTPHARM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('AKUMS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('AKZOINDIA', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('APLLTD', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ALKEM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ALKYLAMINE', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('ALOKINDS', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, TRUE, TRUE),
('ARE&M', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('AMBER', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('AMBUJACEM', 'Construction Materials', 'Construction Materials', FALSE, TRUE, TRUE, TRUE, TRUE),
('ANANDRATHI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('ANANTRAJ', 'Realty', 'Realty', FALSE, FALSE, FALSE, TRUE, TRUE),
('ANGELONE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('APARINDS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('APOLLOHOSP', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, TRUE),
('APOLLOTYRE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('APTUS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('ASAHIINDIA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('ASHOKLEY', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('ASIANPAINT', 'Consumer Durables', 'Consumer Durables', TRUE, FALSE, TRUE, TRUE, TRUE),
('ASTERDM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ASTRAZEN', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ASTRAL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('ATHERENERG', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('ATUL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('AUROPHARMA', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, TRUE, TRUE),
('AIIL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('DMART', 'Consumer Services', 'Consumer Services', FALSE, TRUE, TRUE, TRUE, TRUE),
('AXISBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, TRUE),
('BASF', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('BEML', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('BLS', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BSE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BAJAJ-AUTO', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, TRUE),
('BAJFINANCE', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, TRUE),
('BAJAJFINSV', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, TRUE),
('BAJAJHLDNG', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BAJAJHFL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BALKRISIND', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('BALRAMCHIN', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('BANDHANBNK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BANKBARODA', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, TRUE),
('BANKINDIA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('MAHABANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BATAINDIA', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('BAYERCROP', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('BERGEPAINT', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('BDL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('BEL', 'Capital Goods', 'Capital Goods', TRUE, FALSE, TRUE, TRUE, TRUE),
('BHARATFORG', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, TRUE, TRUE),
('BHEL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('BPCL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, TRUE, TRUE),
('BHARTIARTL', 'Telecommunication', 'Telecommunication', TRUE, FALSE, TRUE, TRUE, TRUE),
('BHARTIHEXA', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, TRUE, TRUE),
('BIKAJI', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('BIOCON', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, TRUE, TRUE),
('BSOFT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, TRUE, TRUE),
('BLUEDART', 'Services', 'Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BLUEJET', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('BLUESTARCO', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('BBTC', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('BOSCHLTD', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, TRUE, TRUE),
('FIRSTCRY', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('BRIGADE', 'Realty', 'Realty', FALSE, FALSE, FALSE, TRUE, TRUE),
('BRITANNIA', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, TRUE, TRUE),
('MAPMYINDIA', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, TRUE, TRUE),
('CCL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('CESC', 'Power', 'Power', FALSE, FALSE, FALSE, TRUE, TRUE),
('CGPOWER', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('CRISIL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CAMPUS', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('CANFINHOME', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CANBK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CAPLIPOINT', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('CGCL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CARBORUNIV', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('CASTROLIND', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('CEATLTD', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('CENTRALBK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CDSL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CENTURYPLY', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('CERA', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('CHALET', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CHAMBLFERT', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('CHENNPETRO', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('CHOICEIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CHOLAHLDNG', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CHOLAFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CIPLA', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, TRUE),
('CUB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CLEAN', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('COALINDIA', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, TRUE, TRUE),
('COCHINSHIP', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('COFORGE', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, TRUE, TRUE),
('COHANCE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('COLPAL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, TRUE),
('CAMS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CONCORDBIO', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('CONCOR', 'Services', 'Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('COROMANDEL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('CRAFTSMAN', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('CREDITACC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('CROMPTON', 'Consumer Durables', 'Consumer Durables', FALSE, TRUE, TRUE, TRUE, TRUE),
('CUMMINSIND', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, TRUE),
('CYIENT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, TRUE, TRUE),
('DCMSHRIRAM', 'Diversified', 'Diversified', FALSE, FALSE, FALSE, TRUE, TRUE),
('DLF', 'Realty', 'Realty', FALSE, TRUE, TRUE, TRUE, TRUE),
('DOMS', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('DABUR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, TRUE),
('DALBHARAT', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, TRUE, TRUE),
('DATAPATTNS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('DEEPAKFERT', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('DEEPAKNTR', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('DELHIVERY', 'Services', 'Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('DEVYANI', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('DIVISLAB', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, TRUE, TRUE),
('DIXON', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, TRUE, TRUE),
('AGARWALEYE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('LALPATHLAB', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('DRREDDY', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, TRUE),
('DUMMYHDLVR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('EIDPARRY', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('EIHOTEL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('EICHERMOT', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, TRUE),
('ELECON', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('ELGIEQUIP', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('EMAMILTD', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('EMCURE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ENDURANCE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('ENGINERSIN', 'Construction', 'Construction', FALSE, FALSE, FALSE, TRUE, TRUE),
('ERIS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('ESCORTS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('ETERNAL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('EXIDEIND', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('NYKAA', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('FEDERALBNK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('FACT', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('FINCABLES', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('FINPIPE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('FSL', 'Services', 'Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('FIVESTAR', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('FORCEMOT', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, TRUE, TRUE),
('FORTIS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('GAIL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, TRUE, TRUE, TRUE, TRUE),
('GVT&D', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GMRAIRPORT', 'Services', 'Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('GRSE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GICRE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('GILLETTE', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GLAND', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('GLAXO', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('GLENMARK', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('MEDANTA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('GODIGIT', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('GPIL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GODFRYPHLP', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GODREJAGRO', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GODREJCP', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, TRUE),
('GODREJIND', 'Diversified', 'Diversified', FALSE, FALSE, FALSE, TRUE, TRUE),
('GODREJPROP', 'Realty', 'Realty', FALSE, FALSE, FALSE, TRUE, TRUE),
('GRANULES', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, TRUE, TRUE),
('GRAPHITE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('GRASIM', 'Construction Materials', 'Construction Materials', TRUE, FALSE, TRUE, TRUE, TRUE),
('GRAVITA', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, TRUE, TRUE),
('GESHIP', 'Services', 'Services', FALSE, FALSE, FALSE, TRUE, TRUE),
('FLUOROCHEM', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, TRUE, TRUE),
('GUJGASLTD', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('GMDCLTD', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, TRUE, TRUE),
('GSPL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, TRUE, TRUE),
('HEG', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('HBLENGINE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, TRUE, TRUE),
('HCLTECH', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, FALSE, TRUE),
('HDFCAMC', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('HDFCBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('HDFCLIFE', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('HFCL', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('HAPPSTMNDS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('HAVELLS', 'Consumer Durables', 'Consumer Durables', FALSE, TRUE, TRUE, FALSE, TRUE),
('HEROMOTOCO', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, FALSE, TRUE),
('HEXT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('HSCL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('HINDALCO', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, FALSE, TRUE),
('HAL', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, FALSE, TRUE),
('HINDCOPPER', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('HINDPETRO', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, TRUE, TRUE, FALSE, TRUE),
('HINDUNILVR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, FALSE, TRUE),
('HINDZINC', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('POWERINDIA', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('HOMEFIRST', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('HONASA', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('HONAUT', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('HUDCO', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('HYUNDAI', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('ICICIBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('ICICIGI', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('ICICIPRULI', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('IDBI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IDFCFIRSTB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IFCI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IIFL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('INOXINDIA', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('IRB', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('IRCON', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('ITCHOTELS', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('ITC', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, FALSE, TRUE),
('ITI', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDGN', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDIACEM', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDIAMART', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDIANB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IEX', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDHOTEL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IOC', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, TRUE, TRUE, FALSE, TRUE),
('IOB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IRCTC', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IRFC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IREDA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IGL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDUSTOWER', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDUSINDBK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('NAUKRI', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('INFY', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, FALSE, TRUE),
('INOXWIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('INTELLECT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('INDIGO', 'Services', 'Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('IGIL', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IKS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('IPCALAB', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('JBCHEPHARM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('JKCEMENT', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, TRUE),
('JBMA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('JKTYRE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('JMFINANCIL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('JSWCEMENT', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, TRUE),
('JSWENERGY', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('JSWINFRA', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('JSWSTEEL', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, FALSE, TRUE),
('JPPOWER', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('J&KBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('JINDALSAW', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('JSL', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('JINDALSTEL', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('JIOFIN', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('JUBLFOOD', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('JUBLINGREA', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('JUBLPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('JWL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('JYOTHYLAB', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('JYOTICNC', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('KPRMILL', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, TRUE),
('KEI', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('KPITTECH', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('KSB', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('KAJARIACER', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, TRUE),
('KPIL', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('KALYANKJIL', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, TRUE),
('KARURVYSYA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('KAYNES', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('KEC', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('KFINTECH', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('KIRLOSBROS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('KIRLOSENG', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('KOTAKBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('KIMS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('LTF', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('LTTS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('LICHSGFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('LTFOODS', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('LTIM', 'Information Technology', 'Information Technology', FALSE, TRUE, TRUE, FALSE, TRUE),
('LT', 'Construction', 'Construction', TRUE, FALSE, TRUE, FALSE, TRUE),
('LATENTVIEW', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('LAURUSLABS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('THELEELA', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('LEMONTREE', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('LICI', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('LINDEINDIA', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('LLOYDSME', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('LODHA', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, TRUE),
('LUPIN', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, FALSE, TRUE),
('MMTC', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MRF', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('MGL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, TRUE),
('MAHSCOOTER', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MAHSEAMLES', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('M&MFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('M&M', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, FALSE, TRUE),
('MANAPPURAM', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MRPL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, TRUE),
('MANKIND', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('MARICO', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, FALSE, TRUE),
('MARUTI', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, FALSE, TRUE),
('MFSL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MAXHEALTH', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, FALSE, TRUE),
('MAZDOCK', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('METROPOLIS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('MINDACORP', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('MSUMI', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('MOTILALOFS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MPHASIS', 'Information Technology', 'Information Technology', FALSE, TRUE, TRUE, FALSE, TRUE),
('MCX', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MUTHOOTFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('NATCOPHARM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('NBCC', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('NCC', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('NHPC', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('NLCINDIA', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('NMDC', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('NSLNISP', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('NTPCGREEN', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('NTPC', 'Power', 'Power', TRUE, FALSE, TRUE, FALSE, TRUE),
('NH', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('NATIONALUM', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('NAVA', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('NAVINFLUOR', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('NESTLEIND', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, FALSE, TRUE),
('NETWEB', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('NEULANDLAB', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('NEWGEN', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('NAM-INDIA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('NIVABUPA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('NUVAMA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('NUVOCO', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, TRUE),
('OBEROIRLTY', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, TRUE),
('ONGC', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, FALSE, TRUE),
('OIL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, TRUE),
('OLAELEC', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('OLECTRA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('PAYTM', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('ONESOURCE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('OFSS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('POLICYBZR', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('PCBL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('PGEL', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, TRUE),
('PIIND', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('PNBHOUSING', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('PTCIL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('PVRINOX', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, TRUE),
('PAGEIND', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, TRUE),
('PATANJALI', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('PERSISTENT', 'Information Technology', 'Information Technology', FALSE, TRUE, TRUE, FALSE, TRUE),
('PETRONET', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, TRUE),
('PFIZER', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('PHOENIXLTD', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, TRUE),
('PIDILITIND', 'Chemicals', 'Chemicals', FALSE, TRUE, TRUE, FALSE, TRUE),
('PPLPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('POLYMED', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('POLYCAB', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('POONAWALLA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('PFC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('POWERGRID', 'Power', 'Power', TRUE, FALSE, TRUE, FALSE, TRUE),
('PRAJIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('PREMIERENE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('PRESTIGE', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, TRUE),
('PGHH', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('PNB', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('RRKABEL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('RBLBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('RECLTD', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('RHIM', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('RITES', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('RADICO', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('RVNL', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('RAILTEL', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('RAINBOW', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('RKFORGE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('RCF', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('REDINGTON', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('RELIANCE', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, FALSE, TRUE),
('RELINFRA', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('RPOWER', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('SBFC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SBICARD', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SBILIFE', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('SJVN', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('SRF', 'Chemicals', 'Chemicals', FALSE, TRUE, TRUE, FALSE, TRUE),
('SAGILITY', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('SAILIFE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('SAMMAANCAP', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('MOTHERSON', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, FALSE, TRUE),
('SAPPHIRE', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SARDAEN', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('SAREGAMA', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, TRUE),
('SCHAEFFLER', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('SCHNEIDER', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('SCI', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SHREECEM', 'Construction Materials', 'Construction Materials', FALSE, TRUE, TRUE, FALSE, TRUE),
('SHRIRAMFIN', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('SHYAMMETL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('ENRIN', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('SIEMENS', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, FALSE, TRUE),
('SIGNATURE', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, TRUE),
('SOBHA', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, TRUE),
('SOLARINDS', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('SONACOMS', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('SONATSOFTW', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('STARHEALTH', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SBIN', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, FALSE, TRUE),
('SAIL', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, TRUE),
('SUMICHEM', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('SUNPHARMA', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, FALSE, TRUE),
('SUNTV', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, TRUE),
('SUNDARMFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SUNDRMFAST', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('SUPREMEIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('SUZLON', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('SWANCORP', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('SWIGGY', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('SYNGENE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('SYRMA', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TBOTEK', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('TVSMOTOR', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, FALSE, TRUE),
('TATACHEM', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, TRUE),
('TATACOMM', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('TCS', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, FALSE, TRUE),
('TATACONSUM', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, FALSE, TRUE),
('TATAELXSI', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('TATAINVEST', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('TMPV', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('TATAPOWER', 'Power', 'Power', FALSE, TRUE, TRUE, FALSE, TRUE),
('TATASTEEL', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, FALSE, TRUE),
('TATATECH', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('TTML', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('TECHM', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, FALSE, TRUE),
('TECHNOE', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, TRUE),
('TEJASNET', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('NIACL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('RAMCOCEM', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, TRUE),
('THERMAX', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TIMKEN', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TITAGARH', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TITAN', 'Consumer Durables', 'Consumer Durables', TRUE, FALSE, TRUE, FALSE, TRUE),
('TORNTPHARM', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, FALSE, TRUE),
('TORNTPOWER', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, TRUE),
('TARIL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TRENT', 'Consumer Services', 'Consumer Services', FALSE, TRUE, TRUE, FALSE, TRUE),
('TRIDENT', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, TRUE),
('TRIVENI', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TRITURBINE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('TIINDIA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('UCOBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('UNOMINDA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('UPL', 'Chemicals', 'Chemicals', FALSE, TRUE, TRUE, FALSE, TRUE),
('UTIAMC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('ULTRACEMCO', 'Construction Materials', 'Construction Materials', TRUE, FALSE, TRUE, FALSE, TRUE),
('UNIONBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('UBL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('UNITDSPR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('USHAMART', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('VGUARD', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, TRUE),
('DBREALTY', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('VTL', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, TRUE),
('VBL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, FALSE, TRUE),
('MANYAVAR', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('VEDL', 'Metals & Mining', 'Metals & Mining', FALSE, TRUE, TRUE, FALSE, TRUE),
('VENTIVE', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('VIJAYA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('VMM', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('IDEA', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, TRUE),
('VOLTAS', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, TRUE),
('WAAREEENER', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('WELCORP', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('WELSPUNLIV', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, TRUE),
('WHIRLPOOL', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, TRUE),
('WIPRO', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, FALSE, TRUE),
('WOCKPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, TRUE),
('YESBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, TRUE),
('ZFCVINDIA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, TRUE),
('ZEEL', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, TRUE),
('ZENTEC', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, TRUE),
('ZENSARTECH', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, TRUE),
('ZYDUSLIFE', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, FALSE, TRUE),
('ECLERX', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, TRUE);
