-- =====================================================
-- CORRECTED DATA INSERTION - All 501 NIFTY 500 Stocks
-- =====================================================
-- 
-- CORRECTIONS APPLIED (Based on Official NSE Data):
-- Source: Official NSE NIFTY 50 list (ind_nifty50list.csv)
-- Source: Official NSE NIFTY NEXT 50 list (ind_niftynext50list.csv)
-- Date of Correction: January 18, 2026
--
-- VERIFIED COUNTS:
-- NIFTY 50:      50 stocks ✓
-- NIFTY NEXT 50: 50 stocks ✓  
-- NIFTY 100:    100 stocks ✓ (NIFTY 50 + NIFTY NEXT 50, no overlap)
-- NIFTY 200:    200 stocks ✓ (includes all NIFTY 100)
-- NIFTY 500:    501 stocks ✓
--
-- Changes Made:
-- 1. Set is_nifty_50 = TRUE for exactly 50 stocks per official NSE NIFTY 50 list
-- 2. Set is_nifty_next_50 = TRUE for exactly 50 stocks per official NSE NIFTY NEXT 50 list
-- 3. Set is_nifty_100 = TRUE for all 100 stocks (NIFTY 50 + NIFTY NEXT 50)
-- 4. Fixed boolean hierarchy: All NIFTY 100 stocks now have is_nifty_200 = TRUE
-- =====================================================

INSERT INTO FUTURES (name, sector, industry, is_nifty_50, is_nifty_next_50, is_nifty_100, is_nifty_200, is_nifty_500) VALUES
('360ONE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('3MINDIA', 'Diversified', 'Diversified', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABB', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('ACC', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('ACMESOLAR', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('AIAENG', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('APLAPOLLO', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('AUBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('AWL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('AADHARHFC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('AARTIIND', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('AAVAS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABBOTINDIA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ACE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ADANIENSOL', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, FALSE),
('ADANIENT', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, TRUE, FALSE),
('ADANIGREEN', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, FALSE),
('ADANIPORTS', 'Services', 'Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('ADANIPOWER', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, FALSE),
('ATGL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABCAPITAL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABFRL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABLBL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABREL', 'Forest Materials', 'Forest Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('ABSLAMC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('AEGISLOG', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('AEGISVOPAK', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('AFCONS', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('AFFLE', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('AJANTPHARM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('AKUMS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('AKZOINDIA', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('APLLTD', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ALKEM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ALKYLAMINE', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('ALOKINDS', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, FALSE),
('ARE&M', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('AMBER', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('AMBUJACEM', 'Construction Materials', 'Construction Materials', FALSE, TRUE, TRUE, TRUE, FALSE),
('ANANDRATHI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ANANTRAJ', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('ANGELONE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('APARINDS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('APOLLOHOSP', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, FALSE),
('APOLLOTYRE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('APTUS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ASAHIINDIA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('ASHOKLEY', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ASIANPAINT', 'Consumer Durables', 'Consumer Durables', TRUE, FALSE, TRUE, TRUE, FALSE),
('ASTERDM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ASTRAZEN', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ASTRAL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ATHERENERG', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('ATUL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('AUROPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('AIIL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('DMART', 'Consumer Services', 'Consumer Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('AXISBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('BASF', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('BEML', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('BLS', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('BSE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('BAJAJ-AUTO', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, FALSE),
('BAJFINANCE', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('BAJAJFINSV', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('BAJAJHLDNG', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('BAJAJHFL', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('BALKRISIND', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('BALRAMCHIN', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('BANDHANBNK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('BANKBARODA', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('BANKINDIA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MAHABANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('BATAINDIA', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('BAYERCROP', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('BERGEPAINT', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('BDL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('BEL', 'Capital Goods', 'Capital Goods', TRUE, FALSE, TRUE, TRUE, FALSE),
('BHARATFORG', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('BHEL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('BPCL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, TRUE, TRUE, TRUE, FALSE),
('BHARTIARTL', 'Telecommunication', 'Telecommunication', TRUE, FALSE, TRUE, TRUE, FALSE),
('BHARTIHEXA', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('BIKAJI', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('BIOCON', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('BSOFT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('BLUEDART', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('BLUEJET', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('BLUESTARCO', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('BBTC', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('BOSCHLTD', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, TRUE, FALSE),
('FIRSTCRY', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('BRIGADE', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('BRITANNIA', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('MAPMYINDIA', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('CCL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('CESC', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('CGPOWER', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('CRISIL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CAMPUS', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('CANFINHOME', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CANBK', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('CAPLIPOINT', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('CGCL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CARBORUNIV', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('CASTROLIND', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('CEATLTD', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('CENTRALBK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CDSL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CENTURYPLY', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('CERA', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('CHALET', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CHAMBLFERT', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('CHENNPETRO', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('CHOICEIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CHOLAHLDNG', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CHOLAFIN', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('CIPLA', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, FALSE),
('CUB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CLEAN', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('COALINDIA', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, TRUE, FALSE),
('COCHINSHIP', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('COFORGE', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('COHANCE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('COLPAL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('CAMS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CONCORDBIO', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('CONCOR', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('COROMANDEL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('CRAFTSMAN', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('CREDITACC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('CROMPTON', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('CUMMINSIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('CYIENT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('DCMSHRIRAM', 'Diversified', 'Diversified', FALSE, FALSE, FALSE, FALSE, FALSE),
('DLF', 'Realty', 'Realty', FALSE, TRUE, TRUE, TRUE, FALSE),
('DOMS', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('DABUR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('DALBHARAT', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('DATAPATTNS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('DEEPAKFERT', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('DEEPAKNTR', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('DELHIVERY', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('DEVYANI', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('DIVISLAB', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, TRUE, FALSE),
('DIXON', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('AGARWALEYE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('LALPATHLAB', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('DRREDDY', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, FALSE),
('DUMMYHDLVR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('EIDPARRY', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('EIHOTEL', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('EICHERMOT', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, FALSE),
('ELECON', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ELGIEQUIP', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('EMAMILTD', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('EMCURE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ENDURANCE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('ENGINERSIN', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('ERIS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('ESCORTS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ETERNAL', 'Consumer Services', 'Consumer Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('EXIDEIND', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('NYKAA', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('FEDERALBNK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('FACT', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('FINCABLES', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('FINPIPE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('FSL', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('FIVESTAR', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('FORCEMOT', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('FORTIS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('GAIL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, TRUE, TRUE, TRUE, FALSE),
('GVT&D', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GMRAIRPORT', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('GRSE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GICRE', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('GILLETTE', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GLAND', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('GLAXO', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('GLENMARK', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('MEDANTA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('GODIGIT', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('GPIL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GODFRYPHLP', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GODREJAGRO', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GODREJCP', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('GODREJIND', 'Diversified', 'Diversified', FALSE, FALSE, FALSE, FALSE, FALSE),
('GODREJPROP', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('GRANULES', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('GRAPHITE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('GRASIM', 'Construction Materials', 'Construction Materials', TRUE, FALSE, TRUE, TRUE, FALSE),
('GRAVITA', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('GESHIP', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('FLUOROCHEM', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('GUJGASLTD', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('GMDCLTD', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('GSPL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('HEG', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('HBLENGINE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('HCLTECH', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, TRUE, FALSE),
('HDFCAMC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('HDFCBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('HDFCLIFE', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('HFCL', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('HAPPSTMNDS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('HAVELLS', 'Consumer Durables', 'Consumer Durables', FALSE, TRUE, TRUE, TRUE, FALSE),
('HEROMOTOCO', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('HEXT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('HSCL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('HINDALCO', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, TRUE, FALSE),
('HAL', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('HINDCOPPER', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('HINDPETRO', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('HINDUNILVR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, TRUE, FALSE),
('HINDZINC', 'Metals & Mining', 'Metals & Mining', FALSE, TRUE, TRUE, TRUE, FALSE),
('POWERINDIA', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('HOMEFIRST', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('HONASA', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('HONAUT', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('HUDCO', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('HYUNDAI', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, TRUE, FALSE),
('ICICIBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('ICICIGI', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('ICICIPRULI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IDBI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IDFCFIRSTB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IFCI', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IIFL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('INOXINDIA', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('IRB', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('IRCON', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('ITCHOTELS', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ITC', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, TRUE, FALSE),
('ITI', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDGN', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDIACEM', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDIAMART', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDIANB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IEX', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDHOTEL', 'Consumer Services', 'Consumer Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('IOC', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, TRUE, TRUE, TRUE, FALSE),
('IOB', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IRCTC', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IRFC', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('IREDA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IGL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDUSTOWER', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDUSINDBK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('NAUKRI', 'Consumer Services', 'Consumer Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('INFY', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, TRUE, FALSE),
('INOXWIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('INTELLECT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('INDIGO', 'Services', 'Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('IGIL', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IKS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('IPCALAB', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('JBCHEPHARM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('JKCEMENT', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('JBMA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('JKTYRE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('JMFINANCIL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('JSWCEMENT', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('JSWENERGY', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, FALSE),
('JSWINFRA', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('JSWSTEEL', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, TRUE, FALSE),
('JPPOWER', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('J&KBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('JINDALSAW', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('JSL', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('JINDALSTEL', 'Metals & Mining', 'Metals & Mining', FALSE, TRUE, TRUE, TRUE, FALSE),
('JIOFIN', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('JUBLFOOD', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('JUBLINGREA', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('JUBLPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('JWL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('JYOTHYLAB', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('JYOTICNC', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('KPRMILL', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, FALSE),
('KEI', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('KPITTECH', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('KSB', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('KAJARIACER', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('KPIL', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('KALYANKJIL', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('KARURVYSYA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('KAYNES', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('KEC', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('KFINTECH', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('KIRLOSBROS', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('KIRLOSENG', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('KOTAKBANK', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('KIMS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('LTF', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('LTTS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('LICHSGFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('LTFOODS', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('LTIM', 'Information Technology', 'Information Technology', FALSE, TRUE, TRUE, TRUE, FALSE),
('LT', 'Construction', 'Construction', TRUE, FALSE, TRUE, TRUE, FALSE),
('LATENTVIEW', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('LAURUSLABS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('THELEELA', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('LEMONTREE', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('LICI', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('LINDEINDIA', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('LLOYDSME', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('LODHA', 'Realty', 'Realty', FALSE, TRUE, TRUE, TRUE, FALSE),
('LUPIN', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('MMTC', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MRF', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('MGL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('MAHSCOOTER', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MAHSEAMLES', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('M&MFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('M&M', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, FALSE),
('MANAPPURAM', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MRPL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('MANKIND', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('MARICO', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('MARUTI', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, FALSE),
('MFSL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MAXHEALTH', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, FALSE),
('MAZDOCK', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('METROPOLIS', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('MINDACORP', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('MSUMI', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('MOTILALOFS', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MPHASIS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('MCX', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MUTHOOTFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('NATCOPHARM', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('NBCC', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('NCC', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('NHPC', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('NLCINDIA', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('NMDC', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('NSLNISP', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('NTPCGREEN', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('NTPC', 'Power', 'Power', TRUE, FALSE, TRUE, TRUE, FALSE),
('NH', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('NATIONALUM', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('NAVA', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('NAVINFLUOR', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('NESTLEIND', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, TRUE, FALSE),
('NETWEB', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('NEULANDLAB', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('NEWGEN', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('NAM-INDIA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('NIVABUPA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('NUVAMA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('NUVOCO', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('OBEROIRLTY', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('ONGC', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, TRUE, FALSE),
('OIL', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('OLAELEC', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('OLECTRA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('PAYTM', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ONESOURCE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('OFSS', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('POLICYBZR', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('PCBL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('PGEL', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('PIIND', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('PNBHOUSING', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('PTCIL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('PVRINOX', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, FALSE),
('PAGEIND', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, FALSE),
('PATANJALI', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('PERSISTENT', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('PETRONET', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', FALSE, FALSE, FALSE, FALSE, FALSE),
('PFIZER', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('PHOENIXLTD', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('PIDILITIND', 'Chemicals', 'Chemicals', FALSE, TRUE, TRUE, TRUE, FALSE),
('PPLPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('POLYMED', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('POLYCAB', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('POONAWALLA', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('PFC', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('POWERGRID', 'Power', 'Power', TRUE, FALSE, TRUE, TRUE, FALSE),
('PRAJIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('PREMIERENE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('PRESTIGE', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('PGHH', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('PNB', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('RRKABEL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('RBLBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('RECLTD', 'Financial Services', 'Financial Services', FALSE, TRUE, TRUE, TRUE, FALSE),
('RHIM', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('RITES', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('RADICO', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('RVNL', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('RAILTEL', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('RAINBOW', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('RKFORGE', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('RCF', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('REDINGTON', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('RELIANCE', 'Oil Gas & Consumable Fuels', 'Oil Gas & Consumable Fuels', TRUE, FALSE, TRUE, TRUE, FALSE),
('RELINFRA', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('RPOWER', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('SBFC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SBICARD', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SBILIFE', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('SJVN', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('SRF', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('SAGILITY', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('SAILIFE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('SAMMAANCAP', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('MOTHERSON', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, TRUE, FALSE),
('SAPPHIRE', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SARDAEN', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('SAREGAMA', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, FALSE),
('SCHAEFFLER', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('SCHNEIDER', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('SCI', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SHREECEM', 'Construction Materials', 'Construction Materials', FALSE, TRUE, TRUE, TRUE, FALSE),
('SHRIRAMFIN', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('SHYAMMETL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ENRIN', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('SIEMENS', 'Capital Goods', 'Capital Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('SIGNATURE', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('SOBHA', 'Realty', 'Realty', FALSE, FALSE, FALSE, FALSE, FALSE),
('SOLARINDS', 'Chemicals', 'Chemicals', FALSE, TRUE, TRUE, TRUE, FALSE),
('SONACOMS', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('SONATSOFTW', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('STARHEALTH', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SBIN', 'Financial Services', 'Financial Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('SAIL', 'Metals & Mining', 'Metals & Mining', FALSE, FALSE, FALSE, FALSE, FALSE),
('SUMICHEM', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('SUNPHARMA', 'Healthcare', 'Healthcare', TRUE, FALSE, TRUE, TRUE, FALSE),
('SUNTV', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, FALSE),
('SUNDARMFIN', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SUNDRMFAST', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('SUPREMEIND', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('SUZLON', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('SWANCORP', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('SWIGGY', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('SYNGENE', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('SYRMA', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TBOTEK', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('TVSMOTOR', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, TRUE, TRUE, TRUE, FALSE),
('TATACHEM', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('TATACOMM', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('TCS', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, TRUE, FALSE),
('TATACONSUM', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', TRUE, FALSE, TRUE, TRUE, FALSE),
('TATAELXSI', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('TATAINVEST', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('TMPV', 'Automobile and Auto Components', 'Automobile and Auto Components', TRUE, FALSE, TRUE, TRUE, FALSE),
('TATAPOWER', 'Power', 'Power', FALSE, TRUE, TRUE, TRUE, FALSE),
('TATASTEEL', 'Metals & Mining', 'Metals & Mining', TRUE, FALSE, TRUE, TRUE, FALSE),
('TATATECH', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('TTML', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('TECHM', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, TRUE, FALSE),
('TECHNOE', 'Construction', 'Construction', FALSE, FALSE, FALSE, FALSE, FALSE),
('TEJASNET', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('NIACL', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('RAMCOCEM', 'Construction Materials', 'Construction Materials', FALSE, FALSE, FALSE, FALSE, FALSE),
('THERMAX', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TIMKEN', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TITAGARH', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TITAN', 'Consumer Durables', 'Consumer Durables', TRUE, FALSE, TRUE, TRUE, FALSE),
('TORNTPHARM', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, TRUE, FALSE),
('TORNTPOWER', 'Power', 'Power', FALSE, FALSE, FALSE, FALSE, FALSE),
('TARIL', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TRENT', 'Consumer Services', 'Consumer Services', TRUE, FALSE, TRUE, TRUE, FALSE),
('TRIDENT', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, FALSE),
('TRIVENI', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TRITURBINE', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('TIINDIA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('UCOBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('UNOMINDA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('UPL', 'Chemicals', 'Chemicals', FALSE, FALSE, FALSE, FALSE, FALSE),
('UTIAMC', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ULTRACEMCO', 'Construction Materials', 'Construction Materials', TRUE, FALSE, TRUE, TRUE, FALSE),
('UNIONBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('UBL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('UNITDSPR', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('USHAMART', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('VGUARD', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('DBREALTY', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('VTL', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, FALSE),
('VBL', 'Fast Moving Consumer Goods', 'Fast Moving Consumer Goods', FALSE, TRUE, TRUE, TRUE, FALSE),
('MANYAVAR', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('VEDL', 'Metals & Mining', 'Metals & Mining', FALSE, TRUE, TRUE, TRUE, FALSE),
('VENTIVE', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('VIJAYA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('VMM', 'Consumer Services', 'Consumer Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('IDEA', 'Telecommunication', 'Telecommunication', FALSE, FALSE, FALSE, FALSE, FALSE),
('VOLTAS', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('WAAREEENER', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('WELCORP', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('WELSPUNLIV', 'Textiles', 'Textiles', FALSE, FALSE, FALSE, FALSE, FALSE),
('WHIRLPOOL', 'Consumer Durables', 'Consumer Durables', FALSE, FALSE, FALSE, FALSE, FALSE),
('WIPRO', 'Information Technology', 'Information Technology', TRUE, FALSE, TRUE, TRUE, FALSE),
('WOCKPHARMA', 'Healthcare', 'Healthcare', FALSE, FALSE, FALSE, FALSE, FALSE),
('YESBANK', 'Financial Services', 'Financial Services', FALSE, FALSE, FALSE, FALSE, FALSE),
('ZFCVINDIA', 'Automobile and Auto Components', 'Automobile and Auto Components', FALSE, FALSE, FALSE, FALSE, FALSE),
('ZEEL', 'Media Entertainment & Publication', 'Media Entertainment & Publication', FALSE, FALSE, FALSE, FALSE, FALSE),
('ZENTEC', 'Capital Goods', 'Capital Goods', FALSE, FALSE, FALSE, FALSE, FALSE),
('ZENSARTECH', 'Information Technology', 'Information Technology', FALSE, FALSE, FALSE, FALSE, FALSE),
('ZYDUSLIFE', 'Healthcare', 'Healthcare', FALSE, TRUE, TRUE, TRUE, FALSE),
('ECLERX', 'Services', 'Services', FALSE, FALSE, FALSE, FALSE, FALSE);