INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (1, '360ONE', 'Financial Services', 'Asset Management');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (2, '3MINDIA', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (3, 'ABB', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (4, 'ACC', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (5, 'ACMESOLAR', 'Utilities', 'Utilities - Renewable');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (6, 'AIAENG', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (7, 'APLAPOLLO', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (8, 'AUBANK', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (9, 'AWL', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (10, 'AADHARHFC', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (11, 'AARTIIND', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (12, 'AAVAS', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (13, 'ABBOTINDIA', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (14, 'ACE', 'Industrials', 'Farm & Heavy Construction Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (15, 'ADANIENSOL', 'Utilities', 'Utilities - Independent Power Producers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (16, 'ADANIENT', 'Energy', 'Thermal Coal');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (17, 'ADANIGREEN', 'Utilities', 'Utilities - Renewable');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (18, 'ADANIPORTS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME,SECTOR,INDUSTRY) VALUES (19, 'ADANIPOWER', 'Utilities', 'Utilities - Independent Power Producers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (20, 'ATGL', 'Utilities', 'Utilities - Regulated Gas');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (21, 'ABCAPITAL', 'Financial Services', 'Financial Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (22, 'ABFRL', 'Consumer Cyclical', 'Apparel Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (23, 'ABREL', 'Basic Materials', 'Paper & Paper Products');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (24, 'ABSLAMC', 'Financial Services', 'Asset Management');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (25, 'AEGISLOG', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (26, 'AFCONS', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (27, 'AFFLE', 'Communication Services', 'Advertising Agencies');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (28, 'AJANTPHARM', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (29, 'AKUMS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (30, 'APLLTD', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (31, 'ALIVUS', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (32, 'ALKEM', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (33, 'ALKYLAMINE', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (34, 'ALOKINDS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (35, 'ARE&M', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (36, 'AMBER', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (37, 'AMBUJACEM', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (38, 'ANANDRATHI', 'Financial Services', 'Asset Management');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (39, 'ANANTRAJ', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (40, 'ANGELONE', 'Financial Services', 'Capital Markets');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (41, 'APARINDS', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (42, 'APOLLOHOSP', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (43, 'APOLLOTYRE', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (44, 'APTUS', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (45, 'ASAHIINDIA', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (46, 'ASHOKLEY', 'Industrials', 'Farm & Heavy Construction Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (47, 'ASIANPAINT', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (48, 'ASTERDM', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (49, 'ASTRAZEN', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (50, 'ASTRAL', 'Industrials', 'Building Products & Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (51, 'ATUL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (52, 'AUROPHARMA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (53, 'AIIL', 'Financial Services', 'Capital Markets');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (54, 'DMART', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (55, 'AXISBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (56, 'BASF', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (57, 'BEML', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (58, 'BLS', 'Industrials', 'Specialty Business Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (59, 'BSE', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (60, 'BAJAJ-AUTO', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (61, 'BAJFINANCE', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (62, 'BAJAJFINSV', 'Financial Services', 'Financial Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (63, 'BAJAJHLDNG', 'Financial Services', 'Asset Management');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (64, 'BAJAJHFL', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (65, 'BALKRISIND', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (66, 'BALRAMCHIN', 'Consumer Defensive', 'Confectioners');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (67, 'BANDHANBNK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (68, 'BANKBARODA', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (69, 'BANKINDIA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (70, 'MAHABANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (71, 'BATAINDIA', 'Consumer Cyclical', 'Footwear & Accessories');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (72, 'BAYERCROP', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (73, 'BERGEPAINT', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (74, 'BDL', 'Industrials', 'Aerospace & Defense');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (75, 'BEL', 'Industrials', 'Aerospace & Defense');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (76, 'BHARATFORG', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (77, 'BHEL', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (78, 'BPCL', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (79, 'BHARTIARTL', 'Communication Services', 'Telecom Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (80, 'BHARTIHEXA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (81, 'BIKAJI', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (82, 'BIOCON', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (83, 'BSOFT', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (84, 'BLUEDART', 'Industrials', 'Integrated Freight & Logistics');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (85, 'BLUESTARCO', 'Industrials', 'Building Products & Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (86, 'BBTC', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (87, 'BOSCHLTD', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (88, 'FIRSTCRY', 'Consumer Cyclical', 'Internet Retail');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (89, 'BRIGADE', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (90, 'BRITANNIA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (91, 'MAPMYINDIA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (92, 'CCL', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (93, 'CESC', 'Utilities', 'Utilities - Regulated Electric');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (94, 'CGPOWER', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (95, 'CRISIL', 'Financial Services', 'Financial Data & Stock Exchanges');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (96, 'CAMPUS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (97, 'CANFINHOME', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (98, 'CANBK', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (99, 'CAPLIPOINT', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (100, 'CGCL', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (101, 'CARBORUNIV', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (102, 'CASTROLIND', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (103, 'CEATLTD', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (104, 'CENTRALBK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (105, 'CDSL', 'Financial Services', 'Capital Markets');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (106, 'CENTURYPLY', 'Basic Materials', 'Lumber & Wood Production');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (107, 'CERA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (108, 'CHALET', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (109, 'CHAMBLFERT', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (110, 'CHENNPETRO', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (111, 'CHOLAHLDNG', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (112, 'CHOLAFIN', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (113, 'CIPLA', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (114, 'CUB', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (115, 'CLEAN', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (116, 'COALINDIA', 'Energy', 'Thermal Coal');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (117, 'COCHINSHIP', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (118, 'COFORGE', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (119, 'COHANCE', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (120, 'COLPAL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (121, 'CAMS', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (122, 'CONCORDBIO', 'Healthcare', 'Biotechnology');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (123, 'CONCOR', 'Industrials', 'Railroads');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (124, 'COROMANDEL', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (125, 'CRAFTSMAN', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (126, 'CREDITACC', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (127, 'CROMPTON', 'Consumer Cyclical', 'Furnishings, Fixtures & Appliances');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (128, 'CUMMINSIND', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (129, 'CYIENT', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (130, 'DCMSHRIRAM', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (131, 'DLF', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (132, 'DOMS', 'Industrials', 'Business Equipment & Supplies');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (133, 'DABUR', 'Consumer Defensive', 'Household & Personal Products');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (134, 'DALBHARAT', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (135, 'DATAPATTNS', 'Industrials', 'Aerospace & Defense');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (136, 'DEEPAKFERT', 'Basic Materials', 'Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (137, 'DEEPAKNTR', 'Basic Materials', 'Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (138, 'DELHIVERY', 'Industrials', 'Integrated Freight & Logistics');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (139, 'DEVYANI', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (140, 'DIVISLAB', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (141, 'DIXON', 'Technology', 'Consumer Electronics');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (142, 'LALPATHLAB', 'Healthcare', 'Diagnostics & Research');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (143, 'DRREDDY', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (144, 'DUMMYDBRLT', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (145, 'EIDPARRY', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (146, 'EIHOTEL', 'Consumer Cyclical', 'Lodging');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (147, 'EICHERMOT', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (148, 'ELECON', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (149, 'ELGIEQUIP', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (150, 'EMAMILTD', 'Consumer Defensive', 'Household & Personal Products');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (151, 'EMCURE', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (152, 'ENDURANCE', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (153, 'ENGINERSIN', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (154, 'ERIS', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (155, 'ESCORTS', 'Industrials', 'Farm & Heavy Construction Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (156, 'ETERNAL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (157, 'EXIDEIND', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (158, 'NYKAA', 'Consumer Cyclical', 'Internet Retail');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (159, 'FEDERALBNK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (160, 'FACT', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (161, 'FINCABLES', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (162, 'FINPIPE', 'Industrials', 'Building Products & Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (163, 'FSL', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (164, 'FIVESTAR', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (165, 'FORTIS', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (166, 'GAIL', 'Utilities', 'Utilities - Regulated Gas');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (167, 'GVT&D', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (168, 'GMRAIRPORT', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (169, 'GRSE', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (170, 'GICRE', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (171, 'GILLETTE', 'Consumer Defensive', 'Household & Personal Products');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (172, 'GLAND', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (173, 'GLAXO', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (174, 'GLENMARK', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (175, 'MEDANTA', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (176, 'GODIGIT', 'Financial Services', 'Insurance - Property & Casualty');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (177, 'GPIL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (178, 'GODFRYPHLP', 'Consumer Defensive', 'Tobacco');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (179, 'GODREJAGRO', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (180, 'GODREJCP', 'Consumer Defensive', 'Household & Personal Products');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (181, 'GODREJIND', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (182, 'GODREJPROP', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (183, 'GRANULES', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (184, 'GRAPHITE', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (185, 'GRASIM', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (186, 'GRAVITA', 'Industrials', 'Metal Fabrication');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (187, 'GESHIP', 'Industrials', 'Marine Shipping');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (188, 'FLUOROCHEM', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (189, 'GUJGASLTD', 'Utilities', 'Utilities - Regulated Gas');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (190, 'GMDCLTD', 'Energy', 'Thermal Coal');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (191, 'GNFC', 'Basic Materials', 'Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (192, 'GPPL', 'Industrials', 'Marine Shipping');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (193, 'GSPL', 'Utilities', 'Utilities - Regulated Gas');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (194, 'HEG', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (195, 'HBLENGINE', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (196, 'HCLTECH', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (197, 'HDFCAMC', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (198, 'HDFCBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (199, 'HDFCLIFE', 'Financial Services', 'Insurance - Life');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (200, 'HFCL', 'Technology', 'Communication Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (201, 'HAPPSTMNDS', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (202, 'HAVELLS', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (203, 'HEROMOTOCO', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (204, 'HSCL', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (205, 'HINDALCO', 'Basic Materials', 'Aluminum');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (206, 'HAL', 'Industrials', 'Aerospace & Defense');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (207, 'HINDCOPPER', 'Basic Materials', 'Copper');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (208, 'HINDPETRO', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (209, 'HINDUNILVR', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (210, 'HINDZINC', 'Basic Materials', 'Other Industrial Metals & Mining');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (211, 'POWERINDIA', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (212, 'HOMEFIRST', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (213, 'HONASA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (214, 'HONAUT', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (215, 'HUDCO', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (216, 'HYUNDAI', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (217, 'ICICIBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (218, 'ICICIGI', 'Financial Services', 'Insurance - Diversified');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (219, 'ICICIPRULI', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (220, 'IDBI', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (221, 'IDFCFIRSTB', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (222, 'IFCI', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (223, 'IIFL', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (224, 'INOXINDIA', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (225, 'IRB', 'Industrials', 'Infrastructure Operations');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (226, 'IRCON', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (227, 'ITC', 'Consumer Defensive', 'Tobacco');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (228, 'ITI', 'Technology', 'Communication Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (229, 'INDGN', 'Healthcare', 'Health Information Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (230, 'INDIACEM', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (231, 'INDIAMART', 'Communication Services', 'Internet Content & Information');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (232, 'INDIANB', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (233, 'IEX', 'Financial Services', 'Capital Markets');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (234, 'INDHOTEL', 'Consumer Cyclical', 'Lodging');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (235, 'IOC', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (236, 'IOB', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (237, 'IRCTC', 'Industrials', 'Railroads');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (238, 'IRFC', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (239, 'IREDA', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (240, 'IGL', 'Utilities', 'Utilities - Regulated Gas');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (241, 'INDUSTOWER', 'Communication Services', 'Telecom Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (242, 'INDUSINDBK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (243, 'NAUKRI', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (244, 'INFY', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (245, 'INOXWIND', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (246, 'INTELLECT', 'Technology', 'Software - Application');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (247, 'INDIGO', 'Industrials', 'Airlines');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (248, 'IGIL', 'Basic Materials', 'Other Precious Metals & Mining');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (249, 'IKS', 'Healthcare', 'Health Information Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (250, 'IPCALAB', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (251, 'JBCHEPHARM', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (252, 'JKCEMENT', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (253, 'JBMA', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (254, 'JKTYRE', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (255, 'JMFINANCIL', 'Financial Services', 'Capital Markets');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (256, 'JSWENERGY', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (257, 'JSWHL', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (258, 'JSWINFRA', 'Industrials', 'Marine Shipping');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (259, 'JSWSTEEL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (260, 'JPPOWER', 'Utilities', 'Utilities - Independent Power Producers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (261, 'J&KBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (262, 'JINDALSAW', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (263, 'JSL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (264, 'JINDALSTEL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (265, 'JIOFIN', 'Financial Services', 'Asset Management');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (266, 'JUBLFOOD', 'Consumer Cyclical', 'Restaurants');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (267, 'JUBLINGREA', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (268, 'JUBLPHARMA', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (269, 'JWL', 'Industrials', 'Railroads');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (270, 'JUSTDIAL', 'Communication Services', 'Internet Content & Information');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (271, 'JYOTHYLAB', 'Consumer Defensive', 'Household & Personal Products');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (272, 'JYOTICNC', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (273, 'KPRMILL', 'Consumer Cyclical', 'Textile Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (274, 'KEI', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (275, 'KNRCON', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (276, 'KPITTECH', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (277, 'KAJARIACER', 'Industrials', 'Building Products & Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (278, 'KPIL', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (279, 'KALYANKJIL', 'Consumer Cyclical', 'Luxury Goods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (280, 'KANSAINER', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (281, 'KARURVYSYA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (282, 'KAYNES', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (283, 'KEC', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (284, 'KFINTECH', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (285, 'KIRLOSBROS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (286, 'KIRLOSENG', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (287, 'KOTAKBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (288, 'KIMS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (289, 'LTF', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (290, 'LTTS', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (291, 'LICHSGFIN', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (292, 'LTFOODS', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (293, 'LTIM', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (294, 'LT', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (295, 'LATENTVIEW', 'Industrials', 'Consulting Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (296, 'LAURUSLABS', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (297, 'LEMONTREE', 'Consumer Cyclical', 'Lodging');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (298, 'LICI', 'Financial Services', 'Insurance - Life');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (299, 'LINDEINDIA', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (300, 'LLOYDSME', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (301, 'LODHA', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (302, 'LUPIN', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (303, 'MMTC', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (304, 'MRF', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (305, 'MGL', 'Utilities', 'Utilities - Regulated Gas');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (306, 'MAHSEAMLES', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (307, 'M&MFIN', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (308, 'M&M', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (309, 'MANAPPURAM', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (310, 'MRPL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (311, 'MANKIND', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (312, 'MARICO', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (313, 'MARUTI', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (314, 'MASTEK', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (315, 'MFSL', 'Financial Services', 'Insurance - Life');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (316, 'MAXHEALTH', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (317, 'MAZDOCK', 'Industrials', 'Aerospace & Defense');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (318, 'METROPOLIS', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (319, 'MINDACORP', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (320, 'MSUMI', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (321, 'MOTILALOFS', 'Financial Services', 'Capital Markets');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (322, 'MPHASIS', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (323, 'MCX', 'Financial Services', 'Financial Data & Stock Exchanges');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (324, 'MUTHOOTFIN', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (325, 'NATCOPHARM', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (326, 'NBCC', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (327, 'NCC', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (328, 'NHPC', 'Utilities', 'Utilities - Renewable');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (329, 'NLCINDIA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (330, 'NMDC', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (331, 'NSLNISP', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (332, 'NTPCGREEN', 'Utilities', 'Utilities - Renewable');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (333, 'NTPC', 'Utilities', 'Utilities - Regulated Electric');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (334, 'NH', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (335, 'NATIONALUM', 'Basic Materials', 'Aluminum');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (336, 'NAVA', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (337, 'NAVINFLUOR', 'Basic Materials', 'Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (338, 'NESTLEIND', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (339, 'NETWEB', 'Technology', 'Computer Hardware');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (340, 'NETWORK18', 'Communication Services', 'Entertainment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (341, 'NEULANDLAB', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (342, 'NEWGEN', 'Technology', 'Software - Infrastructure');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (343, 'NAM-INDIA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (344, 'NIVABUPA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (345, 'NUVAMA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (346, 'OBEROIRLTY', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (347, 'ONGC', 'Energy', 'Oil & Gas Integrated');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (348, 'OIL', 'Energy', 'Oil & Gas Integrated');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (349, 'OLAELEC', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (350, 'OLECTRA', 'Industrials', 'Farm & Heavy Construction Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (351, 'PAYTM', 'Technology', 'Software - Infrastructure');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (352, 'OFSS', 'Technology', 'Software - Infrastructure');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (353, 'POLICYBZR', 'Financial Services', 'Insurance Brokers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (354, 'PCBL', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (355, 'PGEL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (356, 'PIIND', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (357, 'PNBHOUSING', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (358, 'PNCINFRA', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (359, 'PTCIL', 'Industrials', 'Metal Fabrication');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (360, 'PVRINOX', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (361, 'PAGEIND', 'Consumer Cyclical', 'Apparel Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (362, 'PATANJALI', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (363, 'PERSISTENT', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (364, 'PETRONET', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (365, 'PFIZER', 'Healthcare', 'Drug Manufacturers - General');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (366, 'PHOENIXLTD', 'Real Estate', 'Real Estate - Diversified');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (367, 'PIDILITIND', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (368, 'PEL', 'Financial Services', 'Financial Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (369, 'PPLPHARMA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (370, 'POLYMED', 'Healthcare', 'Medical Instruments & Supplies');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (371, 'POLYCAB', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (372, 'POONAWALLA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (373, 'PFC', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (374, 'POWERGRID', 'Utilities', 'Utilities - Regulated Electric');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (375, 'PRAJIND', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (376, 'PREMIERENE', 'Technology', 'Solar');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (377, 'PRESTIGE', 'Real Estate', 'Real Estate - Diversified');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (378, 'PNB', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (379, 'RRKABEL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (380, 'RBLBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (381, 'RECLTD', 'Cartera de valores', 'Cartera de valores');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (382, 'RHIM', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (383, 'RITES', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (384, 'RADICO', 'Consumer Defensive', 'Beverages - Wineries & Distilleries');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (385, 'RVNL', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (386, 'RAILTEL', 'Communication Services', 'Telecom Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (387, 'RAINBOW', 'Healthcare', 'Medical Care Facilities');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (388, 'RKFORGE', 'Industrials', 'Metal Fabrication');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (389, 'RCF', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (390, 'RTNINDIA', 'Consumer Cyclical', 'Internet Retail');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (391, 'RAYMONDLSL', 'Consumer Cyclical', 'Apparel Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (392, 'RAYMOND', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (393, 'REDINGTON', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (394, 'RELIANCE', 'Energy', 'Oil & Gas Refining & Marketing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (395, 'RPOWER', 'Utilities', 'Utilities - Independent Power Producers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (396, 'ROUTE', 'Communication Services', 'Telecom Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (397, 'SBFC', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (398, 'SBICARD', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (399, 'SBILIFE', 'Financial Services', 'Insurance - Life');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (400, 'SJVN', 'Utilities', 'Utilities - Renewable');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (401, 'SKFINDIA', 'Industrials', 'Tools & Accessories');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (402, 'SRF', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (403, 'SAGILITY', 'Healthcare', 'Health Information Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (404, 'SAILIFE', 'Healthcare', 'Diagnostics & Research');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (405, 'SAMMAANCAP', 'Financial Services', 'Mortgage Finance');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (406, 'MOTHERSON', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (407, 'SAPPHIRE', 'Consumer Cyclical', 'Restaurants');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (408, 'SARDAEN', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (409, 'SAREGAMA', 'Communication Services', 'Entertainment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (410, 'SCHAEFFLER', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (411, 'SCHNEIDER', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (412, 'SCI', 'Industrials', 'Marine Shipping');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (413, 'SHREECEM', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (414, 'RENUKA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (415, 'SHRIRAMFIN', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (416, 'SHYAMMETL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (417, 'SIEMENS', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (418, 'SIGNATURE', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (419, 'SOBHA', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (420, 'SOLARINDS', 'Basic Materials', 'Specialty Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (421, 'SONACOMS', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (422, 'SONATSOFTW', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (423, 'STARHEALTH', 'Financial Services', 'Insurance - Diversified');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (424, 'SBIN', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (425, 'SAIL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (426, 'SWSOLAR', 'Technology', 'Solar');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (427, 'SUMICHEM', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (428, 'SUNPHARMA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (429, 'SUNTV', 'Portefeuille', 'Portefeuille');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (430, 'SUNDARMFIN', 'Financial Services', 'Credit Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (431, 'SUNDRMFAST', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (432, 'SUPREMEIND', 'Industrials', 'Building Products & Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (433, 'SUZLON', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (434, 'SWANCORP', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (435, 'SWIGGY', 'Consumer Cyclical', 'Internet Retail');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (436, 'SYNGENE', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (437, 'SYRMA', 'Technology', 'Electronic Components');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (438, 'TBOTEK', 'Consumer Cyclical', 'Travel Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (439, 'TVSMOTOR', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (440, 'TANLA', 'Technology', 'Software - Application');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (441, 'TATACHEM', 'Basic Materials', 'Chemicals');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (442, 'TATACOMM', 'Communication Services', 'Telecom Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (443, 'TCS', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (444, 'TATACONSUM', 'Consumer Defensive', 'Packaged Foods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (445, 'TATAELXSI', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (446, 'TATAINVEST', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (447, 'TATAMOTORS', 'Consumer Cyclical', 'Auto Manufacturers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (448, 'TATAPOWER', 'Utilities', 'Utilities - Independent Power Producers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (449, 'TATASTEEL', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (450, 'TATATECH', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (451, 'TTML', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (452, 'TECHM', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (453, 'TECHNOE', 'Industrials', 'Engineering & Construction');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (454, 'TEJASNET', 'Technology', 'Communication Equipment');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (455, 'NIACL', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (456, 'RAMCOCEM', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (457, 'THERMAX', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (458, 'TIMKEN', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (459, 'TITAGARH', 'Industrials', 'Railroads');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (460, 'TITAN', 'Consumer Cyclical', 'Luxury Goods');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (461, 'TORNTPHARM', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (462, 'TORNTPOWER', 'Utilities', 'Utilities - Independent Power Producers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (463, 'TARIL', 'Industrials', 'Electrical Equipment & Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (464, 'TRENT', 'Consumer Cyclical', 'Apparel Retail');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (465, 'TRIDENT', 'Consumer Cyclical', 'Textile Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (466, 'TRIVENI', 'Consumer Defensive', 'Confectioners');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (467, 'TRITURBINE', 'Industrials', 'Specialty Industrial Machinery');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (468, 'TIINDIA', 'Industrials', 'Conglomerates');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (469, 'UCOBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (470, 'UNOMINDA', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (471, 'UPL', 'Basic Materials', 'Agricultural Inputs');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (472, 'UTIAMC', 'Financial Services', 'Asset Management');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (473, 'ULTRACEMCO', 'Basic Materials', 'Building Materials');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (474, 'UNIONBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (475, 'UBL', 'Consumer Defensive', 'Beverages - Brewers');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (476, 'UNITDSPR', 'Consumer Defensive', 'Beverages - Wineries & Distilleries');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (477, 'USHAMART', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (478, 'VGUARD', 'Portfolio', 'Portfolio');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (479, 'DBREALTY', 'Real Estate', 'Real Estate - Development');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (480, 'VTL', 'Consumer Cyclical', 'Textile Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (481, 'VBL', 'Consumer Defensive', 'Beverages - Non-Alcoholic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (482, 'MANYAVAR', 'Consumer Cyclical', 'Apparel Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (483, 'VEDL', 'Basic Materials', 'Other Industrial Metals & Mining');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (484, 'VIJAYA', 'Healthcare', 'Diagnostics & Research');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (485, 'VMM', 'Consumer Cyclical', 'Department Stores');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (486, 'IDEA', 'Communication Services', 'Telecom Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (487, 'VOLTAS', 'Consumer Cyclical', 'Furnishings, Fixtures & Appliances');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (488, 'WAAREEENER', 'Technology', 'Solar');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (489, 'WELCORP', 'Basic Materials', 'Steel');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (490, 'WELSPUNLIV', 'Consumer Cyclical', 'Textile Manufacturing');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (491, 'WESTLIFE', 'Consumer Cyclical', 'Restaurants');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (492, 'WHIRLPOOL', 'Consumer Cyclical', 'Furnishings, Fixtures & Appliances');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (493, 'WIPRO', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (494, 'WOCKPHARMA', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (495, 'YESBANK', 'Financial Services', 'Banks - Regional');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (496, 'ZFCVINDIA', 'Consumer Cyclical', 'Auto Parts');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (497, 'ZEEL', 'Communication Services', 'Broadcasting');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (498, 'ZENTEC', 'Industrials', 'Aerospace & Defense');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (499, 'ZENSARTECH', 'Technology', 'Information Technology Services');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (500, 'ZYDUSLIFE', 'Healthcare', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO NIFTY500 (ID, NAME, SECTOR, INDUSTRY) VALUES (501, 'ECLERX', 'Technology', 'Information Technology Services');


