TRUNCATE TABLE PREDICTION;

INSERT INTO PREDICTION (name, weight, exchange) VALUES
('HDFCBANK', 13.04, 'NSE'),
('RELIANCE', 8.98, 'NSE'),
('ICICIBANK', 8.00, 'NSE'),
('BHARTIARTL', 4.82, 'NSE'),
('INFY', 4.72, 'NSE'),
('LT', 4.05, 'NSE'),
('SBIN', 3.38, 'NSE'),
('AXISBANK', 3.25, 'NSE'),
('M&M', 2.91, 'NSE'),
('TCS', 2.81, 'NSE'),
('ITC', 2.70, 'NSE'),
('KOTAKBANK', 2.67, 'NSE'),
('BAJFINANCE', 2.17, 'NSE'),
('MARUTI', 1.84, 'NSE'),
('HINDUNILVR', 1.77, 'NSE'),
('ETERNAL', 1.58, 'NSE'),
('SUNPHARMA', 1.56, 'NSE'),
('HCLTECH', 1.45, 'NSE'),
('NTPC', 1.35, 'NSE'),
('TATASTEEL', 1.27, 'NSE'),
('TITAN', 1.26, 'NSE'),
('BEL', 1.18, 'NSE'),
('SHRIRAMFIN', 1.17, 'NSE'),
('ULTRACEMCO', 1.14, 'NSE'),
('ADANIPORTS', 1.11, 'NSE'),
('HINDALCO', 1.11, 'NSE'),
('ASIANPAINT', 1.06, 'NSE'),
('POWERGRID', 1.04, 'NSE'),
('BAJAJFINSV', 0.99, 'NSE'),
('INDIGO', 0.95, 'NSE'),
('BAJAJ-AUTO', 0.90, 'NSE'),
('JSWSTEEL', 0.87, 'NSE'),
('TECHM', 0.85, 'NSE'),
('JIOFIN', 0.84, 'NSE'),
('GRASIM', 0.84, 'NSE'),
('EICHERMOT', 0.83, 'NSE'),
('COALINDIA', 0.82, 'NSE'),
('ONGC', 0.79, 'NSE'),
('NESTLEIND', 0.78, 'NSE'),
('TRENT', 0.76, 'NSE'),
('SBILIFE', 0.73, 'NSE'),
('CIPLA', 0.72, 'NSE'),
('WIPRO', 0.65, 'NSE'),
('TMPV', 0.65, 'NSE'),
('TATACONSUM', 0.64, 'NSE'),
('MAXHEALTH', 0.64, 'NSE'),
('DRREDDY', 0.63, 'NSE'),
('APOLLOHOSP', 0.62, 'NSE'),
('HDFCLIFE', 0.61, 'NSE'),
('ADANIENT', 0.50, 'NSE');


-- Banking & Financial Services
UPDATE PREDICTION SET SECTOR = 'Banking' WHERE NAME = 'HDFCBANK';
UPDATE PREDICTION SET SECTOR = 'Banking' WHERE NAME = 'ICICIBANK';
UPDATE PREDICTION SET SECTOR = 'Banking' WHERE NAME = 'SBIN';
UPDATE PREDICTION SET SECTOR = 'Banking' WHERE NAME = 'AXISBANK';
UPDATE PREDICTION SET SECTOR = 'Banking' WHERE NAME = 'KOTAKBANK';

-- Financial Services (NBFCs)
UPDATE PREDICTION SET SECTOR = 'Financial Services' WHERE NAME = 'BAJFINANCE';
UPDATE PREDICTION SET SECTOR = 'Financial Services' WHERE NAME = 'BAJAJFINSV';
UPDATE PREDICTION SET SECTOR = 'Financial Services' WHERE NAME = 'SHRIRAMFIN';
UPDATE PREDICTION SET SECTOR = 'Financial Services' WHERE NAME = 'JIOFIN';

-- Insurance
UPDATE PREDICTION SET SECTOR = 'Insurance' WHERE NAME = 'HDFCLIFE';
UPDATE PREDICTION SET SECTOR = 'Insurance' WHERE NAME = 'SBILIFE';

-- IT Services
UPDATE PREDICTION SET SECTOR = 'IT' WHERE NAME = 'TCS';
UPDATE PREDICTION SET SECTOR = 'IT' WHERE NAME = 'INFY';
UPDATE PREDICTION SET SECTOR = 'IT' WHERE NAME = 'HCLTECH';
UPDATE PREDICTION SET SECTOR = 'IT' WHERE NAME = 'WIPRO';
UPDATE PREDICTION SET SECTOR = 'IT' WHERE NAME = 'TECHM';

-- FMCG (Fast Moving Consumer Goods)
UPDATE PREDICTION SET SECTOR = 'FMCG' WHERE NAME = 'HINDUNILVR';
UPDATE PREDICTION SET SECTOR = 'FMCG' WHERE NAME = 'ITC';
UPDATE PREDICTION SET SECTOR = 'FMCG' WHERE NAME = 'NESTLEIND';
UPDATE PREDICTION SET SECTOR = 'FMCG' WHERE NAME = 'BRITANNIA'; -- Note: Your table shows 'ETERNAL' but should be BRITANNIA
UPDATE PREDICTION SET SECTOR = 'FMCG' WHERE NAME = 'TATACONSUM';

-- Oil & Gas
UPDATE PREDICTION SET SECTOR = 'Oil & Gas' WHERE NAME = 'RELIANCE';
UPDATE PREDICTION SET SECTOR = 'Oil & Gas' WHERE NAME = 'ONGC';

-- Automobiles
UPDATE PREDICTION SET SECTOR = 'Automobile' WHERE NAME = 'MARUTI';
UPDATE PREDICTION SET SECTOR = 'Automobile' WHERE NAME = 'BAJAJ-AUTO';
UPDATE PREDICTION SET SECTOR = 'Automobile' WHERE NAME = 'EICHERMOT';
UPDATE PREDICTION SET SECTOR = 'Automobile' WHERE NAME = 'M&M';
UPDATE PREDICTION SET SECTOR = 'Automobile' WHERE NAME = 'TVSMOTOR'; -- Note: Your table shows 'TMPV'

-- Pharmaceuticals
UPDATE PREDICTION SET SECTOR = 'Pharma' WHERE NAME = 'SUNPHARMA';
UPDATE PREDICTION SET SECTOR = 'Pharma' WHERE NAME = 'DRREDDY';
UPDATE PREDICTION SET SECTOR = 'Pharma' WHERE NAME = 'CIPLA';

-- Metals & Mining
UPDATE PREDICTION SET SECTOR = 'Metals' WHERE NAME = 'TATASTEEL';
UPDATE PREDICTION SET SECTOR = 'Metals' WHERE NAME = 'JSWSTEEL';
UPDATE PREDICTION SET SECTOR = 'Metals' WHERE NAME = 'HINDALCO';
UPDATE PREDICTION SET SECTOR = 'Metals' WHERE NAME = 'COALINDIA';

-- Cement
UPDATE PREDICTION SET SECTOR = 'Cement' WHERE NAME = 'ULTRACEMCO';
UPDATE PREDICTION SET SECTOR = 'Cement' WHERE NAME = 'GRASIM';

-- Telecom
UPDATE PREDICTION SET SECTOR = 'Telecom' WHERE NAME = 'BHARTIARTL';

-- Power & Utilities
UPDATE PREDICTION SET SECTOR = 'Power' WHERE NAME = 'POWERGRID';
UPDATE PREDICTION SET SECTOR = 'Power' WHERE NAME = 'NTPC';

-- Infrastructure & Construction
UPDATE PREDICTION SET SECTOR = 'Infrastructure' WHERE NAME = 'LT';
UPDATE PREDICTION SET SECTOR = 'Infrastructure' WHERE NAME = 'ADANIPORTS';

-- Paints
UPDATE PREDICTION SET SECTOR = 'Paints' WHERE NAME = 'ASIANPAINT';

-- Healthcare
UPDATE PREDICTION SET SECTOR = 'Healthcare' WHERE NAME = 'APOLLOHOSP';
UPDATE PREDICTION SET SECTOR = 'Healthcare' WHERE NAME = 'MAXHEALTH'; -- Note: Should be APOLLOHOSP if duplicate

-- Consumer Durables
UPDATE PREDICTION SET SECTOR = 'Consumer Durables' WHERE NAME = 'TITAN';

-- Retail
UPDATE PREDICTION SET SECTOR = 'Retail' WHERE NAME = 'TRENT';

-- Media & Entertainment
UPDATE PREDICTION SET SECTOR = 'Media' WHERE NAME = 'ADANIENT';

-- Defence
UPDATE PREDICTION SET SECTOR = 'Defence' WHERE NAME = 'BEL';

-- Aviation
UPDATE PREDICTION SET SECTOR = 'Aviation' WHERE NAME = 'INDIGO';


TRUNCATE TABLE Futures;

INSERT INTO Futures (name) VALUES
('HDFCBANK'),
('RELIANCE'),
('ICICIBANK'),
('BHARTIARTL'),
('INFY'),
('LT'),
('SBIN'),
('AXISBANK'),
('M&M'),
('TCS'),
('ITC'),
('KOTAKBANK'),
('BAJFINANCE'),
('MARUTI'),
('HINDUNILVR'),
('ETERNAL'),
('SUNPHARMA'),
('HCLTECH'),
('NTPC'),
('TATASTEEL'),
('TITAN'),
('BEL'),
('SHRIRAMFIN'),
('ULTRACEMCO'),
('ADANIPORTS'),
('HINDALCO'),
('ASIANPAINT'),
('POWERGRID'),
('BAJAJFINSV'),
('INDIGO'),
('BAJAJ-AUTO'),
('JSWSTEEL'),
('TECHM'),
('JIOFIN'),
('GRASIM'),
('EICHERMOT'),
('COALINDIA'),
('ONGC'),
('NESTLEIND'),
('TRENT'),
('SBILIFE'),
('CIPLA'),
('WIPRO'),
('TMPV'),
('TATACONSUM'),
('MAXHEALTH'),
('DRREDDY'),
('APOLLOHOSP'),
('HDFCLIFE'),
('ADANIENT');
